openapi: 3.0.0
info:
  title: Health Tracker API
  description: API for managing user health data, including BMI, calorie tracking, steps, blood pressure, and activities.
  version: 1.0.0
servers:
  - url: https://healthtracker-production-b3a5.up.railway.app
    description: Production server

paths:
  /api/users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of all users
    post:
      summary: Add new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                email:
                  type: string
              example:
                name: "Donald Trump"
                age: 54
                email: "DonaldTrump@gmail.com"
      responses:
        '201':
          description: User added successfully
  /api/users/{user-id}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Details of the user
    delete:
      summary: Delete user by ID
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted successfully
    patch:
      summary: Update user by ID
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                email:
                  type: string
              example:
                name: "Donald J Trump"
                age: 54
                email: "DonaldTrump@gmail.com"
      responses:
        '200':
          description: User updated successfully

  /api/ratings:
    get:
      summary: Get all ratings
      responses:
        '200':
          description: A list of all ratings
    post:
      summary: Add new user rating
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  type: integer
                userId:
                  type: integer
              example:
                rating: 2
                userId: 1
      responses:
        '201':
          description: Rating added successfully

  /api/users/{user-id}/ratings:
    get:
      summary: Get ratings for a specific user
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ratings of the user
    delete:
      summary: Delete user rating
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Rating deleted successfully
    patch:
      summary: Update user rating
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rating:
                  type: integer
              example:
                rating: 4
      responses:
        '200':
          description: Rating updated successfully

  /api/bmi:
    get:
      summary: Get all BMI records
      responses:
        '200':
          description: A list of all BMI records
    post:
      summary: Add new BMI record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                weight:
                  type: number
                height:
                  type: number
                userId:
                  type: integer
              example:
                weight: 67
                height: 1.8
                userId: 2
      responses:
        '201':
          description: BMI record added successfully

  /api/users/{user-id}/bmi:
    get:
      summary: Get BMI record for a specific user
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: BMI record of the user
    delete:
      summary: Delete BMI record for a specific user
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: BMI record deleted successfully
    patch:
      summary: Update BMI record for a specific user
      parameters:
        - in: path
          name: user-id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                weight:
                  type: number
                height:
                  type: number
              example:
                weight: 77
                height: 1.8
      responses:
        '200':
          description: BMI record updated successfully

  /api/calorie:
    get:
      summary: Get all users who want calculated calorie
      responses:
        '200':
          description: A list of calorie data
    post:
      summary: Add new calorie data for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                weight:
                  type: number
                  format: float
                height:
                  type: number
                  format: float
                velocity:
                  type: number
                  format: float
                userId:
                  type: integer
              required: [weight, height, velocity, userId]
      responses:
        '201':
          description: Calorie data added successfully
  /api/users/{user-id}/calorie:
    get:
      summary: Get calorie data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Calorie data for the user
    delete:
      summary: Delete calorie data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Calorie data deleted
    patch:
      summary: Update calorie data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                weight:
                  type: number
                  format: float
                height:
                  type: number
                  format: float
                velocity:
                  type: number
                  format: float
      responses:
        '200':
          description: Calorie data updated

  /api/steps:
    get:
      summary: Get all users who track steps
      responses:
        '200':
          description: A list of step tracking data
    post:
      summary: Add new step tracking data for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                steps:
                  type: integer
                target:
                  type: integer
                userId:
                  type: integer
              required: [steps, target, userId]
      responses:
        '201':
          description: Step tracking data added successfully
  /api/users/{user-id}/steps:
    get:
      summary: Get step tracking data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Step tracking data for the user
    delete:
      summary: Delete step tracking data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Step tracking data deleted
    patch:
      summary: Update step tracking data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                steps:
                  type: integer
                target:
                  type: integer
      responses:
        '200':
          description: Step tracking data updated

  /api/bloodpressure:
    get:
      summary: Get all users who monitor their blood pressure
      responses:
        '200':
          description: A list of blood pressure data
    post:
      summary: Add new blood pressure data for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lowerval:
                  type: integer
                upperval:
                  type: integer
                userId:
                  type: integer
              required: [lowerval, upperval, userId]
      responses:
        '201':
          description: Blood pressure data added successfully
  /api/users/{user-id}/bloodpressure:
    get:
      summary: Get blood pressure data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Blood pressure data for the user
    delete:
      summary: Delete blood pressure data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Blood pressure data deleted
    patch:
      summary: Update blood pressure data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lowerval:
                  type: integer
                upperval:
                  type: integer
      responses:
        '200':
          description: Blood pressure data updated
  /api/activities:
    get:
      summary: Get all users who added activities
      responses:
        '200':
          description: A list of activities
    post:
      summary: Add new activity data for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                duration:
                  type: number
                  format: float
                calories:
                  type: integer
                started:
                  type: string
                  format: date-time
                userId:
                  type: integer
              required: [description, duration, calories, started, userId]
      responses:
        '201':
          description: Activity data added successfully
  /api/users/{user-id}/activities:
    get:
      summary: Get activity data for a specific user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Activity data for the user

